apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notg-reader
  namespace: notg-reader
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - notg-reader.example.com
      secretName: notg-reader-tls
  rules:
    - host: notg-reader.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notg-reader
                port:
                  number: 80
