apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notg-reader-data
  namespace: notg-reader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
